### ISSUE TITLE
[Feature Request] Expose Kafka Configuration Properties via Configuration

### ISSUE THREAD

**Issue by doncisco1979** [ExpediaGroup/pitchfork#206]
**Describe the feature**
Please add a Map of String String to the Kafka Configuration to allow for advanced Kafka Consumer Configuration

**Rational**
This will allow for more fine grain control of the Kafka Consumer exposing all the Kafka Properties available to the Kafka Consumer. In particular, this also allows for connecting to Kafka Clusters which have Security enabled, and required SASL_SSL or other forms of Secure connections.

**Example Scenario**
User A is using a secured Kafka Cluster to store Span Information and needs to connect Pitchfork to this secured Kafka Cluster. They would simply, in their property file, add the following

```
pitchfork:
  ingress:
    kafka:
      enabled: true
      poll-duration-ms: 1000
      number-consumers: 4
      auto-commit-internal-ms: 1000
      enable-auto-commit: true
      auto-offset-reset: "earliest"
      session-timeout-ms: 60000
      bootstrap-servers: kafka-cluster-1.example.com:9092, kafka-cluster-2.example.com:9092, kafka-cluster-3.example.com:9092
      source-topics:
        - zipkin
      source-format: JSON_V2
      consumer:
        properties:
          security.protocol: SASL_SSL
          ssl.endpoint.identification.algorithm: https
          ssl.truststore.location: <location of pks file>
          ssl.truststore.password: <ssl truststore password>
          sasl.mechanism: PLAIN
          sasl.jaas.config: <jass config>
```
